name: eshop-backing-services
services:
  eshopdb:
    container_name: eshopdb
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EShopDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_eshopdb:/var/lib/postgresql
  
  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    restart: always
    ports:
      - "5341:5341"
      - "9091:80"
    

volumes:
  postgres_eshopdb:
